function t281_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');$('#rec'+recid).attr('data-popup-subscribe-inited','y');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');el.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}));if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t281_showPopup(recid);t281_resizePopup(recid);e.preventDefault();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}}
function t281_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t281_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t281_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t281__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t281_lockScroll()},500)}
el.find('.t-popup').mousedown(function(e){if(e.target==this){t281_closePopup(recid)}});el.find('.t-popup__close').click(function(e){t281_closePopup(recid)});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||(url.substring(0,7)!='#price:'&&url.substring(0,7)!='#order:')){t281_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t281_closePopup(recid)}})}
function t281_closePopup(recid){$('body').removeClass('t-body_popupshowed t281__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t281_unlockScroll()}
setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t281_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t281_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');el.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},200));if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t390_showPopup(recid);t390_resizePopup(recid);e.preventDefault();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){$('#rec'+recid).find('a[href^="#"]:not([href="#"],[href^="#price"],[href^="#popup"],[href^="#prodpopup"],[href^="#order"],a[href^="#!"]),a[href^="'+curPath+'#"]:not(a[href*="#!/tproduct/"],a[href*="#!/tab/"],[href*="#popup"]),a[href^="'+curFullPath+'#"]:not(a[href*="#!/tproduct/"],a[href*="#!/tab/"],[href*="#popup"])').click(function(e){e.preventDefault();var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}
function t390_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed');el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t390_closePopup(recid)}});el.find('.t-popup__close').click(function(e){t390_closePopup(recid)});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t390_closePopup(recid)}})}
function t390_closePopup(recid){$('body').removeClass('t-body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t390_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
t422_setHeight=function(recid){if($(window).width()>960){t422_checkEqualHeight(recid)}else{$('#rec'+recid+' .t422__img-mobile').height(200);$('#rec'+recid+' .t422__text').height('auto')}};t422_checkEqualHeight=function(recid){var t422__txtel=$('#rec'+recid+' .t422__text');var t422__imgel=$('#rec'+recid+' .t422__img');var t422__textwrapperel=$('#rec'+recid+' .t422__textwrapper');var t422__borderwidth=0;if(t422__txtel.css("border-top-width")&&t422__txtel.css("border-top-width")[1]!='p'){t422__borderwidth=+(t422__txtel.css("border-top-width")[0]+t422__txtel.css('border-top-width')[1])}else{if(t422__txtel.css("border-top-width"))
t422__borderwidth=+(t422__txtel.css("border-top-width")[0])}
if(t422__imgel.height()<(t422__textwrapperel.outerHeight()+t422__borderwidth*2)){t422__imgel.height(t422__textwrapperel.outerHeight()+t422__borderwidth*2)}else{if((t422__imgel.height()-t422__borderwidth*2)>t422__textwrapperel.outerHeight()){t422__textwrapperel.outerHeight(t422__imgel.height()-t422__borderwidth*2)}}};function t650_unifyHeights(recid){if($(window).width()>=960){$('#rec'+recid+' .t650 .t-container .t650__row').each(function(){var t650_highestBox=0,t650_currow=$(this);$('.t650__inner-col',this).each(function(){var t650_curCol=$(this),t650_curText=t650_curCol.find(".t650__text"),t650_curBtn=t650_curCol.find(".t650__btn-container"),t650_curColHeight=t650_curText.outerHeight()+t650_curBtn.outerHeight();if(t650_curColHeight>t650_highestBox){t650_highestBox=t650_curColHeight}});$('.t650__inner-col',this).css('height',t650_highestBox)})}else{$('.t650__inner-col').css('height','auto')}}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t704_onSuccess(t704_form){var t704_inputsWrapper=t704_form.find('.t-form__inputsbox');var t704_inputsHeight=t704_inputsWrapper.height();var t704_inputsOffset=t704_inputsWrapper.offset().top;var t704_inputsBottom=t704_inputsHeight+t704_inputsOffset;var t704_targetOffset=t704_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t704_target=t704_targetOffset-200}else{var t704_target=t704_targetOffset-100}
if(t704_targetOffset>$(window).scrollTop()||($(document).height()-t704_inputsBottom)<($(window).height()-100)){t704_inputsWrapper.addClass('t704__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t704_target},400);setTimeout(function(){t704_inputsWrapper.addClass('t704__inputsbox_hidden')},400)}
var successurl=t704_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t722_onSuccess(t722_form){var t722_inputsWrapper=t722_form.find('.t-form__inputsbox');var t722_inputsHeight=t722_inputsWrapper.height();var t722_inputsOffset=t722_inputsWrapper.offset().top;var t722_inputsBottom=t722_inputsHeight+t722_inputsOffset;var t722_targetOffset=t722_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t722_target=t722_targetOffset-200}else{var t722_target=t722_targetOffset-100}
if(t722_targetOffset>$(window).scrollTop()||($(document).height()-t722_inputsBottom)<($(window).height()-100)){t722_inputsWrapper.addClass('t722__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t722_target},400);setTimeout(function(){t722_inputsWrapper.addClass('t722__inputsbox_hidden')},400)}
var successurl=t722_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t722_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);el.find(".t-cover__container").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t983_init(recid){var rec=$('#rec'+recid);t983_unifyHeights(recid);t983_translateBlock(recid);$(window).on('resize',t_throttle(function(){if(typeof window.noAdaptive!='undefined'&&window.noAdaptive==!0&&window.isMobile){return}
t983_unifyHeights(recid);t983_translateBlock(recid)}));$(window).on('load',function(){t983_unifyHeights(recid);t983_translateBlock(recid)});rec.find('.t983').on('displayChanged',t_throttle(function(){t983_unifyHeights(recid);t983_translateBlock(recid)}))}
function t983_translateBlock(recid){var el=$('#rec'+recid);var blockHover=el.find('.t983__card-block_hover');var wrapMarginBottom=35;var isMobile=window.isMobile||$(window).width()<960;blockHover.each(function(){var block=$(this);var blockWrapper=block.parents('.t983__card-block-wrapper');var colWrapHeight=block.parents('.t983__card').height();var diff=colWrapHeight-block.outerHeight()-wrapMarginBottom*2;var blockDiff=block.find('.t983__card-hide').outerHeight();blockWrapper.css('transform','translateY('+diff+'px)');if(!isMobile){block.css('transform','translateY('+blockDiff+'px)')}else{block.css('transform','')}});if(blockHover.length===0){var row=(isMobile?el.find('.t983__container'):el.find('.t983__row'));row.each(function(){var block=$(this).find('.t983__card-block');var maxHeightInRow=0;var colWrapHeight=block.parents('.t983__card').height();block.each(function(){var blockDescHeight=$(this).find('.t983__card-hide').outerHeight();if(blockDescHeight>maxHeightInRow){maxHeightInRow=blockDescHeight}});block.each(function(){var blockTitleHeight=$(this).find('.t983__card-show').outerHeight();var diff=colWrapHeight-blockTitleHeight-maxHeightInRow-wrapMarginBottom*2;$(this).css('transform','translateY('+diff+'px)')})})}}
function t983_unifyHeights(recid){var el=$('#rec'+recid);el.find('.t983 .t-container .t983__row').each(function(){var highestBox=0;var currow=$(this);var curwidth=currow.find('.t983__card').width();var ratio=el.find('.t983__container').attr('data-ratio');var minHeightFromRatio=0;switch(ratio){case '16_9':minHeightFromRatio=curwidth*0.5625;break;case '4_3':minHeightFromRatio=curwidth*0.75;break;case '3_2':minHeightFromRatio=curwidth*0.6666;break;case '1_1':minHeightFromRatio=curwidth;break;case '2_3':minHeightFromRatio=curwidth*1.5;break;case '3_4':minHeightFromRatio=curwidth*1.3333;break;case '9_16':minHeightFromRatio=curwidth*1.7777;break}
currow.find('.t983__card-content').each(function(){var cardContent=$(this);var colHeight=cardContent.outerHeight();if(colHeight>highestBox){highestBox=colHeight}});if(highestBox>minHeightFromRatio){currow.find('.t983__card-wrapper').css('padding-bottom',highestBox+'px')}else{currow.find('.t983__card-wrapper').css('padding-bottom','')}})}